### ISSUE TITLE
Having IPFS default empty folder in denylist prevents ipfs+nopfs-kubo-plugin from starting

### ISSUE THREAD

**Issue by liteua** [ipfs-shipyard/nopfs#12]
Hi!
After adding default IPFS empty folder to denylist ipfs daemon is not able to start anymore:
```
ipfs  | 2023-07-12T11:05:55.613Z        INFO    nopfs   nopfs-kubo-plugin/plugin.go:59  Loading Nopfs plugin: content blocking
ipfs  | 2023-07-12T11:05:56.599Z        INFO    nopfs   nopfs@v0.0.8/denylist.go:165    Processing /data/ipfs/.config/ipfs/denylists/test-list.deny: test-list (test list for trying nopfs) by None
ipfs  | 2023-07-12T11:05:56.602Z        ERROR   core    core/builder.go:158     constructing the node: could not build arguments for function "reflect".makeFuncStub (reflect/asm_amd64.s:28): failed to build *mfs.Root: received non-nil error from function "github.com/ipfs/kubo/core/node".Files (github.com/ipfs/kubo@v0.21.0/core/node/core.go:136): failure writing to dagstore: QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn is blocked and cannot be provided
ipfs  |
ipfs  | Error: constructing the node (see log for full detail): failure writing to dagstore: QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn is blocked and cannot be provided
```
configuration for the denylist:
```
name: "test-list"
---
/ipfs/QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn
```
As this CID is present in badbits lists - we cannot just download and use those lists as-is, we need to remove line with hash "//6fe4a9f9ee915120a76ac47bf396198b02a1457dd1234ab75b2c394ca8ef5779" before using it. Not sure if its a bug, or maybe some notification in the documentation about this could be enough.

**Comment by hsanjuan** [comment]
Hi, the empty folder CID has now been removed from the badbits list. The error happens because the MFS root (`ipfs files`) is probably an empty folder.

This was essentially due to a mistake in the badbits. I'm not sure if it is actionable here (i.e. hardcoding an exception). An additional workaround might be to have a different custom denylist with just an exception for this CID (i.e `+/ipfs/QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn`). If that list is processed *before* (I think that means it should alphabetically come before badbits.deny, it should override the blocking entry.
