### ISSUE TITLE
Inconsistent file watcher

### ISSUE THREAD

**Issue by AlexMCon** [ipfs-shipyard/nopfs#16]
Tried to adjust a deny list with a python package through the open / write functions. Sometimes the plugin takes notice of the change, sometimes it does not. My code looks something like this (not proficient in Python by any means):

`with open(os.path.expanduser(ipfsFilePath), "wt", encoding="utf-8") as ipfs_cids_file:
                ipfs_cids_file.write('\n'.join(list(map(lambda x: '//' + x, cids))) + '\n')`

It has inconsistent behaviour both in deletion and in addition of cids.

How I'm testing the addition of new cids:
1. Upload the file to the GUI
2. Hash the file's CID with sha-256
3. Take hash and add it to the .deny file through the code above that runs in a python package
4. Check in GUI if I can pin the file
5. Sometimes it works, but most of the time it does not

I'm testing the deletion of cids in the same way, the only difference being that I run the ipfs daemon already having the hash inside the deny list (and it obviously does not allow me to pin the file), then I delete the line through the python code from the .deny list and I try again. Most of the time it still blocks it, even though the line was deleted.

**Comment by hsanjuan** [comment]
I don't understand that you upload a file and then add it to the denylist, then check if it can be pinned (which should fail if it is on the deny list).

The first thing to say is that the file-watcher only takes notice of "append" operations. Things added after the last line are read. Deleting things somewhere in the file will cause issues unless the full file is reprocessed. The right way to "unblock" a previously added file so that things work is to add a new "negated" line, prepending with `!`: `!/ipfs/<cid>`.

Second, check that your python is actually writing the file. I can't do much python, but I think you are missing `a` among your `open` options, which means you intend to "append" to the file: https://docs.python.org/3/library/functions.html#open

Otherwise you might be overwriting from the beginning etc. which will confuse the watcher. The watcher just triggers a notification on file modification indicating that we can keep reading from the place where we reached the End Of File before and only from there, until we reach EOF again.

**Comment by AlexMCon** [comment]
Hello! Tyvm for your answer. Sorry for my delayed reply. Managed to implement what you suggested some time ago (2-3 weeks) and it worked fine. Append + always negating what was before if necessary. So ty!

**Comment by AlexMCon** [comment]
Works fine!
